name: Build Master JSON

on:
  push:
    branches:
      - main
    paths:
      - 'settings/**.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Generate master JSON
      id: merge-json
      run: node scripts/ci-build-master-json.js

    - name: Generate .oldconfig files
      run: node scripts/ci-generate-oldconfigs.js

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add master.json oldconfig/*
        git commit -m "Update master.json and .oldconfig files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
